export const INITIAL_STITCHES = 20;
export const INITIAL_ROWS = 25;
export const INITIAL_WIDTH = 10;
export const INITIAL_LENGTH = 10;
export const INITIAL_BLANKET_WIDTH = 60;
export const INITIAL_BLANKET_LENGTH = 120;

//Socks constants
export const INITIAL_SIZE_FOOT = 0;
export const INITIAL_FOOT_CIRCUM = 0;
export const INITIAL_HEEL_DIAGONAL = 0;
export const INITIAL_CALF_CIRCUM = 0;
export const INITIAL_TOTAL_SOCKS_STITCHES = 0;
export const INITIAL_HEEL_STITCHES = 0;
export const INITIAL_GUSSET_STITCHES = 0;
export const INITIAL_HEEL_FLAP_STITCHES = 0;
export const INITIAL_INSTEP_STITCHES = 0;
export const INITIAL_REM_FLAP_STITCHES = 0;
export const INITIAL_NUM_STITCHES_BEFORE_PICK_HEEL_FLAP = 0;
export const INITIAL_PICK_HEEL_FLAP_STITCHES = 0;
export const INITIAL_HEEL_FLAP_LENGTH = 0;
export const INITIAL_DECREASE_GUSSET_STITCHES = 0;
export const INITIAL_SOCKS_LENGTH = 0;
export const INITIAL_DECREASE_TOE_STITCHES = 0;
export const INITIAL_TOE_ROWS = 0;
export const INITIAL_TOE_LENGTH = 0;
